[mypy]
show_error_codes = True
warn_unused_ignores = True
# Duplicate module names (also exist in examples/advanced/)
exclude = (examples/tutorial/marco_musmss_enumeration\.py|examples/advanced/ocus_explanations\.py)

# TODO: fix tools.xcsp3 later
[mypy-cpmpy.tools.xcsp3]
ignore_errors = True
[mypy-cpmpy.tools.xcsp3.*]
ignore_errors = True

# the template is not real code...
[mypy-cpmpy.solvers.TEMPLATE]
ignore_errors = True


# untyped external solvers
[mypy-cplex.*]
ignore_missing_imports = True

[mypy-docplex.*]
ignore_missing_imports = True

[mypy-exact.*]
ignore_missing_imports = True

[mypy-gcspy.*]
ignore_missing_imports = True

[mypy-gurobipy.*]
ignore_missing_imports = True

[mypy-hexaly.*]
ignore_missing_imports = True

[mypy-minizinc.*]
ignore_missing_imports = True

[mypy-pindakaas.*]
ignore_missing_imports = True

[mypy-pumpkin_solver.*]
ignore_missing_imports = True

[mypy-pychoco.*]
ignore_missing_imports = True

[mypy-pypblib.*]
ignore_missing_imports = True

[mypy-pysat.*]
ignore_missing_imports = True

[mypy-pysdd.*]
ignore_missing_imports = True

[mypy-z3.*]
ignore_missing_imports = True

# untyped pycsp3, used in tools.xcsp3
[mypy-pycsp3.*]
ignore_missing_imports = True
