name: Github Tests
on: [push] # Can also put pull_request here, but then we dont run it when directly pushing to master
jobs:
  test:
    strategy:
      fail-fast: true # cancel all jobs as soon as one solver test suite fails
      matrix:
        include:
          - solver: ortools
          - solver: z3
          - solver: pysat
            install_commands: |
              pip install pypblib
          - solver: choco
          - solver: exact
          - solver: gcs
          - solver: minizinc
            install_commands: |
              sudo snap install minizinc --classic
          - solver: pindakaas
          - solver: pumpkin
          - solver: scip
          - solver: highs
    uses: ./.github/workflows/test-solver.yml
    with:
      solver: ${{ matrix.solver }}
      install_commands: ${{ matrix.install_commands || '' }}
